[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev:vite"
  targetPort = 5177
  port = 8888

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200
